---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: backend
  labels:
    app: mongodb
    tier: database
spec:
  selector:
    app: mongodb
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: backend
  labels:
    app: mongodb
    tier: database
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: database
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: database
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017